name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3
  - ipywidgets=7.5.1
  - jupyterlab=1.2.0
  - jupyter_contrib_nbextensions
  - lxml
  - matplotlib=3.1.1
  - nodejs=12.8
  - numpy=1.17.0
  - pandas=0.25.1
  - pandas-profiling=2.3.0
  - pip
  - pillow=6.2.1
  - python=3.7
  - scikit-learn=0.22
  - scipy=1.3.1
  - seaborn=0.9.0
  - vega_datasets
  - pip:
    - datachile


